version: '3.8'

services:
  
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    env_file:
      - ${ENV_FILE}
  
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: nest-db